13.Django/my_poll_cbv/config/urls.py
# config/urls.py
from django.contrib import admin
from django.urls import path, include
from polls import urls
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include("polls.urls")), # url시작이 polls이면 polls/urls.py의 urlpattern을 참고해라
    path('', TemplateView.as_view(template_name="home.html"), name='home')
]

13.Django/my_poll_cbv/polls/urls.py
# urls.py url -  View 연결
# polls/urls.py -> polls app용 url pattern 설정스크립트

from django.urls import path
from . import views
from .models import Question
from django.views.generic import ListView, DetailView

# 이 url pattern의 namespace(prefix)로 사용할 값 설정
# app 설정의 이름 호출 시 다른 app과 구분하기 위해 사용
app_name = "polls"

urlpatterns = [
    # CBV를 등록: ViewClass이름.as_view()
    # path("list", views.QuestionListView.as_view(), name='list'),
    path('list', ListView.as_view(model=Question, template_name="polls/list.html"), name='list'),
    path("form/<int:question_id>", views.VoteView.as_view(), name='vote'),
    # path('vote', views.vote, name='vote'),
    # path('result/<int:pk>', views.QuestionDetailView.as_view(), name='vote_result'),
    path('result/<int:pk>', DetailView.as_view(model=Question, template_name="polls/vote_result.html"), name='vote_result'),
]

13.Django/my_poll_cbv/polls/models.py
from django.db import models

# Question(질문), 
#   - question_text(질문내용)
#   - pub_date(질문 등록일시)
#   - id(PK - 자동생성): 1씩 증가하는 값을 가지도록 자동생성

# Choice(보기)
#   - choice_text(보기내용)
#   - vote(몇번 선택되었는지)
#   - question(어떤 질문에 대한 보기인지 - Question의 Foreign key 컬럼)
#   - id(PK - 자동생성): 1씩 증가하는 값을 가지도록 자동생성

# Model을 상속
# 컬럼과 연결된 Field를 class변수로 선언
class Question(models.Model):
    # 변수명: 컬럼명, 값: Field 객체대입 -> 타입
    question_text = models.CharField(max_length=200) # CharField==NVACHAR
    pub_date = models.DateTimeField(auto_now_add=True) # auto_now_add: insert될 때 일시를 자동등록(insert)

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    choice_text = models.CharField(max_length=200)
    vote = models.PositiveIntegerField(default=0)
    question = models.ForeignKey(to=Question, on_delete=models.CASCADE)
    # to: 참조 Model 클래스(Table) 지정.
    # on_delete: 부모테이블의 값이 delete될 경우 처리방식. CASCADE: 참조하는 자식데이터도 함께 삭제
    def __str__(self):
        return self.choice_text

13.Django/my_poll_cbv/polls/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse # reverse함수 : path 설정 이름으로 url 문자열을 만들어주는 함수

from django.views.generic import ListView, View, DetailView
from .models import Question, Choice

# ListView - 모델의 전체 데이터를 조회해서 template에게 전달. (Paging 기능제공)
class QuestionListView(ListView):
    model = Question # 조회할 모델클래스 지정
    template_name = "polls/list.html" # 응답할 template 경로
    # 조회결과를 template에게 전달 - 이름: '모델클래스명(소문자)_list', 'object_list'
    # 다른이름으로 전달할 경우 : context_object_name = '전송할이름'

# 투표 작업을 처리
# GET 요청: 투표 양식 (vote_form)
# POST 요청: 투표 처리 (vote)
class VoteView(View):
    # get방식 요청 처리
    def get(self, request, *args, **kwargs):
        # kwargs: path parameter를 조회
        print("==========================VoteView.get()")
        question_id = kwargs['question_id']
        try:
            question = Question.objects.get(pk=question_id)
            return render(request, "polls/vote_form.html", {"question":question})
            # 바로 해당 app의 templates 디렉토리에서 조회하므로 경로명은 이를 참고
        except:
            return render(request, 'polls/error.html',
                        {"error_message":"없는 질문을 작성하셨습니다."})
    
    # post방식 요청 처리
    def post(self, request, *args, **kwargs):
        print("==========================VoteView.post()")
        choice_id = request.POST.get('choice')

        # question_id = request.POST.get('question_id')
        question_id = kwargs['question_id']
        if not choice_id:
            question = Question.objects.get(pk=question_id)
            return render(request, 'polls/vote_form.html',
                        {
                            "question":question,
                            "error_message":"보기를 선택하세요."
                        })
        choice = Choice.objects.get(pk=choice_id)
        choice.vote += 1
        choice.save() # pk가 있다면 update, 없으면 insert

        url_str = reverse("polls:vote_result", args=[question_id])
        return redirect(url_str)

# DetailView: 특정 모델의 Primary key를 받아서 조회한 결과를 template에 전달
# primary key는 path parameter로 받아야 한다. urls.py에서 path parameter의 변수명은 <타입:pk>
# question의 id(pk)를 받아서 질문 하나를 조회한 후 template(vote_result.html)로 이동
class QuestionDetailView(DetailView):
    model = Question # 데이터를 조회할 Model 클래스 지정
    template_name = "polls/vote_result.html" # 이동할 template 경로

13.Django/my_poll_cbv/polls/templates/polls/error copy.html
<!-- templates/polls/error.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    사용 도중 문제가 발생했습니다.<br>
    자세한 사항은 관리자에게 문의하세요<br>
    문제원인: {{error_message}}
</body>
</html>

13.Django/my_poll_cbv/polls/templates/polls/error.html
<!-- templates/polls/error.html -->
{% extends "layout.html" %}

{% block title %}에러페이지{% endblock title %}

{% block contents %} 
사용 도중 문제가 발생했습니다.<br>
자세한 사항은 관리자에게 문의하세요<br>
문제원인: {{error_message}}
{% endblock contents %}

13.Django/my_poll_cbv/polls/templates/polls/list copy.html
<!-- template파일: html을 기반 + django문법 - django html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Poll List</title>
</head>
<body>
    <a href='http://daum.net'>Da&nbsp;um</a>
    <!-- &npsb; 요거 하나가 공백하나. 이외의 문자는 전부 공백 하나로 출력 -->
    <a href='http://naver.com'>Naver</a>
    <h2>설문 목록</h2>
    질문 총 개수:{{question_list|length}}
    <ul>
        {% for question in question_list %}
        <li>
            <!-- <a href='/polls/vote_form/{{question.id}}'> -->
            <a href='{% url "polls:vote_form" question.id %}'>
                {{question.question_text | truncatewords:2}}
            </a>
            {{question.pub_date | date:'Y-m-d'}}
        </li>
        {% empty %}
            <b>등록된 질문이 없습니다.</b>
        {% endfor %}
    </ul>
</body>
</html>

13.Django/my_poll_cbv/polls/templates/polls/list.html
<!-- templates/polls/list.html -->
{% extends "layout.html" %}

{% block title %}투표list 페이지{% endblock title %}

{% block contents %}
<a href='http://daum.net'>Da&nbsp;um</a>
<!-- &npsb; 요거 하나가 공백하나. 이외의 문자는 전부 공백 하나로 출력 -->
<a href='http://naver.com'>Naver</a>
<h2>설문 목록</h2>
질문 총 개수:{{question_list|length}}
<ul class="lsit-group">
    {% for question in question_list %}
    <li class="list-group-item">
        <!-- <a href='/polls/vote_form/{{question.id}}'> -->
        <a href='{% url "polls:vote" question.id %}'>
            {{question.question_text | truncatewords:2}}
        </a>
        {{question.pub_date | date:'Y-m-d'}}
    </li>
    {% empty %}
        <b>등록된 질문이 없습니다.</b>
    {% endfor %}
</ul>
{% endblock contents %}

13.Django/my_poll_cbv/polls/templates/polls/vote_form copy.html
<!-- template/polls/vote_form.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>투표</title>
</head>
<body>
    <h1>투표 폼</h1>
    {% if error_message != None %}
    <div style="color:red">
        {{error_message}} {# 출력 태그 - 변수가 없거나 None일 경우 아무것도 출력하지 않음 #}
    </div>
    {% else %}
        <div style='color:blue'>에러메세지가 없습니다.</div>
    {% endif %}
    
    {{question.pk}}.{{question.question_text}}<p>
    <!-- <form action="/polls/vote" method='POST'> -->
    <form action="{% url 'polls:vote' %}" method='POST'>
        {% csrf_token %}{# post방식 요청시 반드시 넣어줘야 한다-csrf 공격을 방지하기 위한 token값을 생성 #}
        {# cross site  forgery #}
        <input type='hidden' name='question_id' value='{{question.pk}}'>
        
        {% for choice in question.choice_set.all %}
            {# choice: Choice모델객체 - template주석 #}
            <input type='radio' name='choice' value='{{choice.pk}}' id="{{choice.pk}}"> {# choice=pk #}
            <label for='{{choice.pk}}'>{{choice.choice_text}}</label><br>
        {% endfor %}
        <input type='submit' value='VOTE'> <button>투표</button>
        <input type='reset' value='RESET'> <button type='reset'>초기화</button>
    </form>
</body>
</html>

{# 한줄 주석 #}

{% comment %}
 block 주석
{% endcomment %}

<!-- HTML 주석 -->

13.Django/my_poll_cbv/polls/templates/polls/vote_form.html
<!--template/polls/vote_form.html-->
{% extends "layout.html" %}

{% block title %}투표폼{% endblock title %}
{% block contents %}
<h1>투표 폼</h1>
{% if error_message != None %}
<div style="color:red">
    {{error_message}} {# 출력 태그 - 변수가 없거나 None일 경우 아무것도 출력하지 않음 #}
</div>
{% else %}
    <div style='color:blue'>에러메세지가 없습니다.</div>
{% endif %}

{{question.pk}}.{{question.question_text}}<p>
<!-- <form action="/polls/vote" method='POST'> -->
<form action="{% url 'polls:vote' question.pk %}" method='POST'>
    {% csrf_token %}{# post방식 요청시 반드시 넣어줘야 한다-csrf 공격을 방지하기 위한 token값을 생성 #}
    {# cross site  forgery #}
    <!-- <input type='hidden' name='question_id' value='{{question.pk}}'> -->
    
    {% for choice in question.choice_set.all %}
        {# choice: Choice모델객체 - template주석 #}
        <input type='radio' name='choice' value='{{choice.pk}}' id="{{choice.pk}}"> {# choice=pk #}
        <label for='{{choice.pk}}'>{{choice.choice_text}}</label><br>
    {% endfor %}
    <input type='submit' value='VOTE' class='btn btn-primary'>
    <button class='btn btn-secondary'>투표</button>
    <input type='reset' value='RESET'class='btn btn-danger'>
    <button type='reset' class='btn btn-warning'>초기화</button>
</form>
{% endblock contents %}

13.Django/my_poll_cbv/polls/templates/polls/vote_result copy.html
<!-- templates/polls/vote_result.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>투표 결과</title>
</head>
<body>
    <h1>투표 결과</h1>
    {{question.pk}}. {{question.question_text}}
    <ol>
        {% for choice in question.choice_set.all %}
        <li>{{choice.choice_text}} - {{choice.vote}}</li>
        {% endfor %}
    </ol>

    <!-- <a href="/polls/list">질문목록</a> -->
    <a href="{% url 'polls:list' %}">질문목록</a>
</body>
</html>

13.Django/my_poll_cbv/polls/templates/polls/vote_result.html
<!-- templates/polls/vote_result.html -->
{% extends "layout.html" %}

{% block title %}투표 결과{% endblock title %}
{% block contents %}
<h1>투표 결과</h1>
{{question.pk}}. {{question.question_text}}
<ol class='list-group'>
    {% for choice in question.choice_set.all %}
    <li class='list-group-item'>{{choice.choice_text}} - {{choice.vote}}</li>
    {% endfor %}
</ol>

<!-- <a href="/polls/list">질문목록</a> -->
<a href="{% url 'polls:list' %}" class='btn btn-warning'>질문목록</a>
{% endblock contents %}

13.Django/my_poll_cbv/templates/home copy.html
<!-- root/templates/home.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>홈</title>
</head>
<body>
    <h1>홈</h1>
    <!-- <a href='/polls/list'>질문 목록</a> -->
    <a href='{% url "polls:list" %}'>질문 목록</a>
    <a href='/admin'>관리</a>
</body>
</html>

13.Django/my_poll_cbv/templates/home.html
<!-- root/templates/home.html -->
{% extends "layout.html" %} <!--layout.html을 상속-->

{% block title %}
메인페이지
{% endblock title %}

{% block contents %}
<h1>홈페이지</h1>
{% endblock contents %}

13.Django/my_poll_cbv/templates/layout.html
<!-- root/templates/layout.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}제목{% endblock %}</title>
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
</head>
<body>
<div class="container">
    <!-- <a href='/polls/list'>질문 목록</a> -->
    <a href='{% url "polls:list" %}'>질문 목록</a>
    <a href='/admin'>관리</a>
    <hr> <!-- 구분선-->
    {% block contents %}
    {% endblock contents %}
</div>
</body>
</html>