13.Django/my_board/board/urls.py
# board/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'board'
urlpatterns = [
    path('detail/<int:pk>', views.PostDetailView.as_view(), name='detail'), # 게시물 상세페이지
    path('create', views.PostCreateView.as_view(), name='create'),          # 글 등록 url
    path('update/<int:pk>', views.PostUpdateView.as_view(), name='update'), # 글 수정 url. GET: 수정할 게시물의 pk를 path parameter 받아야 함
]

13.Django/my_board/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls),
    path('board/', include('board.urls'))
]

13.Django/my_board/board/models.py
from django.db import models

# Create your models here.
# 글의 카테고리
class Category(models.Model):
    # pk - 자동증가 정수 컬럼
    category_code = models.AutoField(primary_key=True)
    # CharField() 문자열 필드
    # 매개변수 verbose_name: 화면에 나올 때 라벨명
    category_name = models.CharField(max_length=200, verbose_name="글 카테고리")

    def __str__(self):
        return f"{self.pk}. {self.category_name}"


# 게시물(글)
# title(제목), content(글내용), create_at(등록 일시), update_at(수정 일시), writer(글쓴이-후에 추가)
class Post(models.Model):
    # 만약 이 값을 pk로 쓰려면 ,primary_key=True) 를 추가
    title = models.CharField(max_length=255, verbose_name="글제목") # Not NULL, 빈문자열 허용x
    content = models.TextField(verbose_name="글내용") # TextField: 대용량 text
    # null=False(기본): not null 여부 - False:Not null, True: null허용컬럼
    # blank=False(기본): 빈 문자열 허용여부
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, verbose_name="글 분류",
                                 null=True, blank=True)
    # 작성일시 auto_now_add=True(기본값:False) => insert 시점의 일시를 저장하고 그 이후에는 update하지 않음
    create_at = models.DateTimeField(verbose_name='작성일시', auto_now_add=True)
    # 수정일시 auto_now=True(기본값:False) => insrt/update할 때마다 그 시점의 일시를 저장
    update_at = models.DateTimeField(verbose_name="최신 수정일시", auto_now=True)

    def __str__(self):
        return f"{self.pk}. {self.title}"

13.Django/my_board/board/forms.py
from django import forms
from .models import Post

# form 클래스 - forms.Form상속
# Model 클래스 - forms.ModelForm 상속
class PostForm(forms.ModelForm):
    # 내부(Nested/inner) 클래스로 Meta 클래스를 정의 => ModelForm 관련 설정
    
    class Meta:
        model = Post # Form을 만들 때 참조할 Model클래스 지정
        fields = "__all__" # create_al, update_at은 auto_now(자동 등록)했기 때문에 Form Field로 사용 안함
        # Model의 Field들 중 Form Field로 만들 Field들 지정. 모두 지정할 경우 문자열로 __all__지정
        # 몇 개만 지정할 경우 리스트에 Field이름을 지정 ex) fields = ['content', 'title']
        # 특정 Field를 제외한 나머지로 지정할 경우 exclude = ['title'] # title 빼고 나머지

13.Django/my_board/board/views.py
from django.shortcuts import render
from django.views.generic import CreateView, DetailView, UpdateView
from django.urls import reverse_lazy

from .forms import PostForm
from .models import Post

# Create your views here.
# 글 등록

# CreateView 등록(저장-insert 처리)
#   get 방식 요청: 입력양식 화면으로 이동(render())
#   post방식 요청: 입력(등록) 처리
#                  성공페이지로 이동(redirect)
#                  처리실패: 입력양식 화면으로 이동(render())
class PostCreateView(CreateView):
    template_name = 'board/post_create.html' # 입력양식 화면 template 경로
    form_class = PostForm # 요청파라미터를 처리할 Form을 지정
    # success_url = reverse_lazy("board:detail") # 등록 처리 후 이동할 경로->redirect방식 이동->view의 url을 등록
    
    # success_url 설정을 대신
    #   success_url에서 insert한 Model객체를 접근하려면 이 메소드를 overriding해야 한다.
    #   insert한 모델 객체 조회: self.objct
    def get_success_url(self):
        # 반환값: 등록 성공 후 redirect 방식으로 이동할 View의 url을 문자열로 반환
        return reverse_lazy('board:detail', args=[self.object.pk]) # args: path parameter로 전달할 값들을 리스트에 순서대로 넣는다.


# 하나의 글 정보 조회(pk)
# DetailView - pk로 조회한 결과를 template으로 보내주는 Generic View
#   url 패턴: pk를 path 파라미터로 받는다. <type:pk> 변수명을 pk로 지정해야 한다.
#             이 path parameter값을 이용해 select
class PostDetailView(DetailView):
    template_name = "board/post_detail.html" # 응답할 template의 경로
    model = Post
    # pk로 조회할 Model 클래스. 조회결과를 "post"(모델클래스명 소문자로 변경), "object"라는 이름으로 template에게 전달


# 글 수정처리
# UpdateView
#  - GET 요청처리: pk로 수정할 정보를 조회해서 template(수정 form)으로 전달
#  - POST요청처리: update 처리. redirect방식으로 View를 요청
#  - template_name: 수정 form template파일의 경로
#  - form_class: Form/ModelForm 클래스 등록
#  - model: Model 클래스 등록 (수정폼 template에 전달할 값을 조회하기 위해)
#  - success_url: 수정 처리 후 redirect방식으로 이동할 View의 url (path parameter로 update한 Model정보를
#                 사용할 경우 get_success_url()를 오버라이딩) 
class PostUpdateView(UpdateView):
    template_name = "board/post_update.html"
    form_class = PostForm
    model = Post

    def get_success_url(self):
        return reverse_lazy('board:detail', args=[self.object.pk])

13.Django/my_board/board/templates/board/post_create.html
{% extends 'layout.html' %}
{% load bootstrap4 %}
{% block title %}글 등록{% endblock title %}
{% block contents %}
<form method='post'>
    {% csrf_token %}
    <!-- {{form.as_p}} -->
    {% bootstrap_form form %}
    <button type='submit' class="btn btn-primary">글등록</button>
    <button type='reset'  class="btn btn-info">초기화</button>
</form>
{% endblock contents %}

13.Django/my_board/board/templates/board/post_detail.html
{% extends "layout.html" %}

{% block title %}글상세{% endblock title %}

{% block contents %}
<!-- 조회결과 변수: object, post -->
<h1 style="border-bottom: 1px solid gray;padding-bottom: 5px;">{{object.pk}}. {{object.title}}</h1>

<div style="border-bottom: 1px solid gray;padding-bottom: 5px;">
    <b>작성일시:</b>:{{object.create_at|date:"Y/m/d H:i:s"}}
    <b>수정일시:</b>:{{object.update_at|date:"Y/m/d H:i:s"}}
    <b>글분류:</b>:{{object.category.category_name}}
</div>
<div style="border-bottom: 1px solid gray;padding-bottom: 5px;min-height: 200px;">
    {{object.content|linebreaksbr}}
</div>
<div>
    <br>
    <a href="{% url 'board:update' object.pk %}" class='btn btn-primary'>글수정</a>
</div>
{% endblock contents %}

13.Django/my_board/board/templates/board/post_update.html
<!-- board/templates/board/post_update.html -->
{% extends "layout.html" %}
{% load bootstrap4 %}

{% block title %}글 수정 폼{% endblock title %}

{% block contents %}
<h1>글 수정폼</h1>
<form method='post'>
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type='submit' class='btn btn-primary'>글수정</button>
    <button type='reset' class='btn btn-info'>초기화</button>
</form>
{% endblock contents %}

13.Django/my_board/templates/home.html
{% extends "layout.html" %}
{% block title %}Home{% endblock title %}
{% block contents %}홈페이지{% endblock contents %}

13.Django/my_board/templates/layout.html
<!-- root/templates/layout.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}제목{% endblock %}</title>
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
</head>
<body>
<div class="container">
    <a href='/admin'>관리</a>
    <a href="{% url 'board:create'%}">글쓰기</a>
    <hr>
    {% block contents %}{% endblock contents %}
</div>
</body>
</html>